package in.ashwanthkumar.gocd.slack.jsonapi;

import java.io.IOException;
import java.net.MalformedURLException;
import java.util.Arrays;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import com.google.gson.annotations.SerializedName;
import com.thoughtworks.go.plugin.api.logging.Logger;

public class MaterialRevision {
    static private final Pattern PIPELINE_REVISION_PATTERN =
        Pattern.compile("^([^/]+)/(\\d+)/.*");

    private Logger LOG = Logger.getLoggerFor(MaterialRevision.class);

    @SerializedName("changed")
    public boolean changed;

    @SerializedName("material")
    public Material material;

    @SerializedName("modifications")
    public Modification[] modifications;

    /**
     * Is this revision a pipeline, or something else (generally a commit
     * to a version control system)?
     */
    public boolean isPipeline() {
        return material.isPipeline();
    }

    /**
     * Collect all changed MaterialRevision objects, walking changed
     * "Pipeline" objects recursively instead of including them directly.
     */
    void addChangesRecursively(Server server, List<MaterialRevision> outChanges)
        throws MalformedURLException, IOException
    {
        // Give up now if this material hasn't changed.
        if (!changed) {
            return;
        }

        if (!isPipeline()) {
            // Add this change if somebody hasn't added it already (which
            // can happen in complex pipelines).
            if (!outChanges.contains(this))
                outChanges.add(this);
        } else {
            // Recursively walk pipeline.  We're not entirely sure what it
            // would mean to have multiple associated modifications with
            // isPipeline is true, so we walk all of them just to be on the
            // safe side.
            for (Modification m : modifications) {
                // Parse out the pipeline info.
                Matcher matcher = PIPELINE_REVISION_PATTERN.matcher(m.revision);
                if (matcher.matches()) {
                    String pipelineName = matcher.group(1);
                    int pipelineCounter = Integer.parseInt(matcher.group(2));

                    // Fetch the pipeline and walk it recursively.
                    Pipeline pipeline =
                        server.getPipelineInstance(pipelineName, pipelineCounter);
                    pipeline.addChangesRecursively(server, outChanges);
                } else {
                    LOG.error("Error matching pipeline revision: " + m.revision);
                }
            }
        }
    }

    // Override hashCode and equals with implementations generated by
    // Eclipse so we can compare MaterialRevision objects using (for
    // example) list.contains(mr).

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + (changed ? 1231 : 1237);
        result = prime * result + ((material == null) ? 0 : material.hashCode());
        result = prime * result + Arrays.hashCode(modifications);
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        MaterialRevision other = (MaterialRevision) obj;
        if (changed != other.changed)
            return false;
        if (material == null) {
            if (other.material != null)
                return false;
        } else if (!material.equals(other.material))
            return false;
        if (!Arrays.equals(modifications, other.modifications))
            return false;
        return true;
    }
}
